### ISSUE TITLE
Can you add //stack and //move ??

### ISSUE THREAD

**Issue by AgentH14** [CzechPMDevs/BuilderTools#10]

**Comment by AgentH14** [comment]
Hey.. I wondering if you could add the //stack and //move commands for this plugin please?
Because just like the Minecraft Java Edition WorldEdit plug-in, you can do the majority of the WorldEdit commands.  So it would be great and highly appreciated and awesome if you could add these 2 commands to the BuilderTools pocketmine plugin.

Thanks.

**Comment by GamakCZ** [comment]
Moved to #32
