### ISSUE TITLE
FullChunkDataPacket Not Found

### ISSUE THREAD

**Issue by maxicode2** [CzechPMDevs/BuilderTools#101]
When doing //set in a large area, I get kicked with [this error message](https://pastebin.com/sjNTDkMJ) in logs.

**Comment by GamakCZ** [comment]
What version are you using?

**Comment by maxicode2** [comment]
I used the lates one from poggit but nvm its already fixed (on github and by myself)

**Comment by maxicode2** [comment]
I used the lates one from poggit but nvm its already fixed (on github and
by myself)
