### ISSUE TITLE
Add the ability to make changes without saving them

### ISSUE THREAD

**Issue by AndreasHGK** [CzechPMDevs/BuilderTools#107]
The main point of this is to be able to be able to paste in big builds without exhausting the server memory. A use case for this could be that you can for example make one fairly big mine and then //stack it without crashing the server. This will of course make it so that you can't undo the changes, so that is why i am asking for it to be an option that can be disabled, maybe in the config or a command argument.

**Comment by VixikHD** [comment]
With the latest commit is this feature useless (plugin is now compressing the clipboard, so ram usage is not a problem anymore)
