### ISSUE TITLE
Add //wall like Nukkit/Java world edit!

### ISSUE THREAD

**Issue by MistakingManx** [CzechPMDevs/BuilderTools#108]
I don't want to be pushy or difficult, I'm extremely thankful for such a nice world edit plugin to even exist for PocketMine-MP, thank you for making this for us and releasing it for free!

This is more of a suggestion / question of sorts, using a similar system to //cyl and //replace would it be possible to implement //walls as-well? (if there's a list of planned features and this is in it, I can be pretty blind at times, I'd like a link to that if it exists, thank you <3)

**Comment by VixikHD** [comment]
Added in last commit!
