### ISSUE TITLE
schematic

### ISSUE THREAD

**Issue by mazepeto** [CzechPMDevs/BuilderTools#109]
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate
4096 bytes) in phar:///root/Sm/PocketMine-MP.phar/src/pocketmine/block/BlockFac
tory.php on line 400 
[05:48:49] [Server thread/CRITICAL]: Could not execute asynchronous task Schemat
icLoadTask: Task crashed

**Comment by VixikHD** [comment]
Your schematics file is too big. Try disable memory limit in pocketmine.yml
