### ISSUE TITLE
not correct //undo

### ISSUE THREAD

**Issue by SuperAdam47** [CzechPMDevs/BuilderTools#111]
1. step run command //sphere 1 3
2. step run command //undo

= 
![image](https://user-images.githubusercontent.com/16169771/89737101-38f89500-da77-11ea-93bf-4fd0c3cdd2b4.png)

**Comment by SuperAdam47** [comment]
hsphere undo's is this 
![image](https://user-images.githubusercontent.com/16169771/89737146-765d2280-da77-11ea-93eb-cbc152ac41a7.png)

**Comment by VixikHD** [comment]
thx for report
