### ISSUE TITLE
INFO Fatal error: Allowed memory size exceeded

### ISSUE THREAD

**Issue by xGrumpyx** [CzechPMDevs/BuilderTools#119]
v 1.2.0-beta2
When schematic files are in the `/schematics` directory, I receive the error message below. The server becomes unstable to the point that it is unusable.

`[Server] INFO Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in phar:///pocketmine/plugins/BuilderTools.phar/src/czechpmdevs/buildertools/editors/object/BlockList.php on line 65
02.09 19:08:14 [Server] Server thread/CRITICAL Could not execute asynchronous task SchematicLoadTask: Task crashed`

**Comment by VixikHD** [comment]
Disable memory limit in pocketmine.yml
