### ISSUE TITLE
Schematics wont work

### ISSUE THREAD

**Issue by Altamash347** [CzechPMDevs/BuilderTools#126]
Please fix schematics, they dont work, please fix it

**Comment by VixikHD** [comment]
I need crashdump or error from the console to fix that bug.

**Comment by UnEnanoMas** [comment]
I think he means that they do not appear in the schematic list when I put them, they do not appear to me either

**Comment by VixikHD** [comment]
Can you record video with reproducing the bug?

**Comment by UnEnanoMas** [comment]
Give me a moment that I'm a little busy, when I can I'll record it for you

**Comment by UnEnanoMas** [comment]
You can close this case now, the schematics work correctly

@VixikHD
