### ISSUE TITLE
The //fix clears slappers

### ISSUE THREAD

**Issue by UnEnanoMas** [CzechPMDevs/BuilderTools#129]
I have used the // fix command for a world with dolls, and when I finish and go, they have disappeared

PS: It would be good if it changed you from world to another when you put //fix to the main one so that it does not crash

**Comment by VixikHD** [comment]
What version are you using?

**Comment by UnEnanoMas** [comment]
dev 89

**Comment by VixikHD** [comment]
So you want fix those bugs:
- [ ] Entities are removed after fixing the world
- [ ] It is possible to fix default level (crashes game)

**Comment by UnEnanoMas** [comment]
Yes, because if you are in the main world and you correct that world, it will crash and take you out

**Comment by VixikHD** [comment]
pm4 fixes this
