### ISSUE TITLE
Error when executing schematics commands

### ISSUE THREAD

**Issue by PatiicDev** [CzechPMDevs/BuilderTools#135]
"Server thread/CRITICAL ErrorException: "Array and string offset access syntax with curly braces is deprecated" (EXCEPTION) in "plugins/BuilderTools (1).phar/src/czechpmdevs/buildertools/schematics/UnloadedSchematic" at line 75
18.02 22:45:38 [Server] Server thread/CRITICAL #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(138): pocketmine\utils\Utils::errorExceptionHandler(integer 8192, string[69] Array and string offset access syntax with curly braces is deprecated, string[142] phar:///plugins/BuilderTools (1).phar, integer 75, array[2])
18.02 22:45:38 [Server] Server thread/CRITICAL #1 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
18.02 22:45:38 [Server] Server thread/CRITICAL #2 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[53] czechpmdevs\buildertools\schematics\UnloadedSchematic)
18.02 22:45:38 [Server] Server thread/CRITICAL #3 (): BaseClassLoader->{closure}(string[53] czechpmdevs\buildertools\schematics\UnloadedSchematic)
18.02 22:45:38 [Server] Server thread/CRITICAL #4 plugins/BuilderTools (1).phar/src/czechpmdevs/buildertools/schematics/SchematicsManager(67): spl_autoload_call(string[53] czechpmdevs\buildertools\schematics\UnloadedSchematic)
18.02 22:45:38 [Server] Server thread/CRITICAL #5 plugins/BuilderTools (1).phar/src/czechpmdevs/buildertools/schematics/SchematicsManager(50): czechpmdevs\buildertools\schematics\SchematicsManager->loadSchematics()
18.02 22:45:38 [Server] Server thread/CRITICAL #6 plugins/BuilderTools (1).phar/src/czechpmdevs/buildertools/BuilderTools(105): czechpmdevs\buildertools\schematics\SchematicsManager->__construct(object czechpmdevs\buildertools\BuilderTools)
18.02 22:45:38 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/plugin/PluginBase(116): czechpmdevs\buildertools\BuilderTools->onEnable()"

This is the error that appears when trying to load some schematics.

**Comment by VixikHD** [comment]
Could you send me schematic file you are trying to load?

**Comment by VixikHD** [comment]
There aren't any depreacated methods used
