### ISSUE TITLE
Use PHP7.3 for poggit

### ISSUE THREAD

**Issue by supercrafter333** [CzechPMDevs/BuilderTools#141]
Please don't use PHP7.4 or heigher because poggit don't approve plugins with PHP7.4 Codes or heigher!

**Comment by VixikHD** [comment]
Using php 7.4 isn't against poggit [rules](https://poggit.pmmp.io/rules.edit). Also we inform people about that they need to use php 7.4 in order to run this plugin.

**Comment by supercrafter333** [comment]
You can ask Jason.
