### ISSUE TITLE
Remove unnecessary blocks

### ISSUE THREAD

**Issue by UnEnanoMas** [CzechPMDevs/BuilderTools#142]
Currently I have tried to correct a map (that weighs more than 2GB) and it has taken 8 hours to correct it, when I finish correcting it, I thought that this type of blocks would eliminate them, but no, they are still there, which generates a lot of lag and The only way to remove these types of blocks and not generate lines across the sky, is to break them or explode them.

I was wondering if there was some way to remove those blocks and thus eliminate all those unnecessary lines.

(API 3.0.0)
![image](https://user-images.githubusercontent.com/63286108/114227716-a0a01080-9975-11eb-9bf9-f89cfc8178b4.png)
![image](https://user-images.githubusercontent.com/63286108/114227800-c0373900-9975-11eb-8d16-47bceaf8452a.png)

**Comment by VixikHD** [comment]
Thank you for report
