### ISSUE TITLE
I want to rotate stair

### ISSUE THREAD

**Issue by mazepeto** [CzechPMDevs/BuilderTools#155]
Currently, the stairs are not rotated. So it’s very uncomfortable

**Comment by VixikHD** [comment]
Could you please specify which angle and axis have you used?

**Comment by mazepeto** [comment]
https://drive.google.com/file/d/14PePWjR6vnPMcWpmYfI9f3fhbRI3fgpP/view?usp=drivesdk

I need to edit the stairs.

**Comment by VixikHD** [comment]
I am not sure stone stairs are implemented in base pocketmine 3.0, are you using some plugin to implement them?

**Comment by mazepeto** [comment]
this version is 4.0.0 .
3.0 version dose not rotate stairs

**Comment by VixikHD** [comment]
I though 4.0 version does not even work 😄 . I will check that next week
