### ISSUE TITLE
//schem paste does not work 

### ISSUE THREAD

**Issue by redstonetechwiz** [CzechPMDevs/BuilderTools#157]
When loading the schematic, everything works fine.

When pasting the schematic, everything works fine, and It says that it has been successfully pasted, but no blocks change. 

Upon checking console it reads “Some chunks were not found” 

 - BuilderTools Version [e.g. dev#142, Release 1.2.0-beta3]

**Comment by VixikHD** [comment]
Could you please attach your schematics file? I think it is caused pasting it to chunks whose are not generated.

**Comment by redstonetechwiz** [comment]
Sure, here it is. It's 250x250 in size.
[ZeldaSkyblockSpawn-bupznb.zip](https://github.com/CzechPMDevs/BuilderTools/files/6541430/ZeldaSkyblockSpawn-bupznb.zip)

**Comment by redstonetechwiz** [comment]
Solved the issue.
For the chunk issue, I went into the config for pocketmine and increased the render distance. I then sat and let all the chunks load before pasting. For the crashing, I increased ram allocation to 8gb and also ensured the pasted file doesnt exceed height limit (as that will return an Internal Error.)
