### ISSUE TITLE
Internel server error on pasting //rotate 90 180 270 in 1.2.0 beta4

### ISSUE THREAD

**Issue by reyyan987** [CzechPMDevs/BuilderTools#158]
I have s build I want to rotate it completely like it is facing south to north I didn't know how to do so I did //rotate 90 180 270 after copying and than I paste it but got internet server error

**Comment by VixikHD** [comment]
Please, use correct template

**Comment by reyyan987** [comment]
Which template

**Comment by VixikHD** [comment]
![image](https://user-images.githubusercontent.com/40556088/120526938-10f96a00-c3da-11eb-8002-eb8660c7fa62.png)
