### ISSUE TITLE
API for third party plugins

### ISSUE THREAD

**Issue by jasonwynn10** [CzechPMDevs/BuilderTools#160]
**Is your feature request related to a problem? Please describe.**
Using the API provided by BuilderTools is difficult at best, and impossible at worst. All relevant API requires a Player object to be passed in, even when it shouldn't be necessary. I'm trying to add BuilderTools support in MyPlot but cannot because I don't have a player object to pass into every function.

**Describe the solution you'd like**
Generalize the API so Player objects are not required for everything.

**Describe alternatives you've considered**
Currently, third party plugins must create a fake player object for BuilderTools to allow API usage when using a real player isn't suitable.

**Additional context**
Required code for API use with fake players:
```php
$fakePlayer = new Player(Server::getInstance(), new NetworkSession(Server::getInstance(), Server::getInstance()->getNetwork()->getSessionManager(), PacketPool::getInstance(), new RakLibPacketSender(99999, new RakLibInterface(Server::getInstance())), new StandardPacketBroadcaster(Server::getInstance()), ZlibCompressor::getInstance(), '127.0.0.1', 19130), new PlayerInfo('selector1', Uuid::uuid4(), new Skin(), 'en_US', []), false, new Location(0,0,0), CompoundTag::create());
Filler::getInstance()->fillDirect($fakePlayer, $plotBeginPos, new Vector3($xMax, World::Y_MAX, $zMax), 'air', false);
```
It's kind of ridiculous

**Comment by VixikHD** [comment]
How about using [FillSession](https://github.com/CzechPMDevs/BuilderTools/blob/default/src/czechpmdevs/buildertools/editors/object/FillSession.php#L34) directly?

**Comment by VixikHD** [comment]
Closed due to inactivity
