### ISSUE TITLE
Could you implement a new function/code to check if the item, block is valid

### ISSUE THREAD

**Issue by NTT1906** [CzechPMDevs/BuilderTools#163]
//set <item1:meta1...>
both item1 and meta1 should be valid and greater than 0? and the meta1 should be lower than 15

sorry for my poor explanations ~~

`//set -1` will cause internal error so i think it's better to have another function to solve that

this isn't necessary though but i think it's better to have it for the plugin stability

**Comment by VixikHD** [comment]
Invalid format
