### ISSUE TITLE
Add fill with random blocks

### ISSUE THREAD

**Issue by reyyan987** [CzechPMDevs/BuilderTools#164]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I want that like you van do random blocks on //fill like grass dirt or other blocks but randomized pls if you already have this pls tell command cause I don't know

**Comment by VixikHD** [comment]
Invalid usage of the template

**Comment by reyyan987** [comment]
I just give example like fill or any other command of ith random blocks
