### ISSUE TITLE
Rotating causes extremely long pause and eventual hard crash (Allowed memory exhausted)

### ISSUE THREAD

**Issue by TheShermanTanker** [CzechPMDevs/BuilderTools#166]
**Describe the bug**
When attempting to rotate a selection with the rotate command that rotates in any axis other than the Y axis, the server freezes before a memory exception crash

**To Reproduce**
1. Set the 1st and second position with the Wand
2. //copy
3. //rotate on any axis other than the Y axis
4. Server freezes before crashing

**Expected behavior**
The selected area should be rotated about an axis after the command is executed

**Screenshots**
![image](https://user-images.githubusercontent.com/32636402/123367335-590c4680-d5ac-11eb-892b-6d3de56d428d.png)

**System information (please complete the following information):**
 - OS: Windows 10
 - php version 7.4
 - BuilderTools Version dev#148, but any 1.2.0 build has this issue
**Additional context**

**Comment by VixikHD** [comment]
How big is the selection? Seems your server has not enough memory. Try enabling clipboard compression.
