### ISSUE TITLE
//fix bug on pm4

### ISSUE THREAD

**Issue by Refaltor77** [CzechPMDevs/BuilderTools#172]
**Command that bug**
When I make the order//fix, an error this product

**System information (please complete the following information):**
 - OS: Debian 10
 - php version 7.4
 - BuilderTools Version [branch pm4]

**Comment by VixikHD** [comment]
Without knowing your PocketMine-MP version, used plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
