### ISSUE TITLE
Error: Invalid subchunk Y coordinate 16

### ISSUE THREAD

**Issue by MrHoller** [CzechPMDevs/BuilderTools#174]
**Describe the bug**
Can use //set 0 to crash server

**To Reproduce**
1. type //wand
2. highlight zone
3. type //set 0
4. error
```
PocketMine-MP Crash Dump Wed Sep 1 20:48:32 UTC 2021

Error: Invalid subchunk Y coordinate 16
File: pmsrc/src/world/format/Chunk
Line: 320
Type: InvalidArgumentException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: BuilderTools v1.3.0-beta1

Code:
[311] 		$this->terrainDirtyFlags = ~0;
[312] 	}
[313] 
[314] 	public function clearTerrainDirtyFlags() : void{
[315] 		$this->terrainDirtyFlags = 0;
[316] 	}
[317] 
[318] 	public function getSubChunk(int $y) : SubChunk{
[319] 		if($y < 0 || $y >= $this->subChunks->getSize()){
[320] 			throw new \InvalidArgumentException("Invalid subchunk Y coordinate $y");
[321] 		}
[322] 		return $this->subChunks[$y];
[323] 	}
[324] 
[325] 	/**
[326] 	 * Sets a subchunk in the chunk index
[327] 	 */
[328] 	public function setSubChunk(int $y, ?SubChunk $subChunk) : void{
[329] 		if($y < 0 or $y >= $this->subChunks->getSize()){
[330] 			throw new \InvalidArgumentException("Invalid subchunk Y coordinate $y");

Backtrace:
#0 plugins/BuilderTools/src/czechpmdevs/buildertools/editors/object/FillSession(216): pocketmine\world\format\Chunk->getSubChunk(integer 16)
#1 plugins/BuilderTools/src/czechpmdevs/buildertools/editors/object/FillSession(78): czechpmdevs\buildertools\editors\object\FillSession->moveTo(integer 157, integer 256, integer 352)
#2 plugins/BuilderTools/src/czechpmdevs/buildertools/editors/Filler(71): czechpmdevs\buildertools\editors\object\FillSession->setBlockAt(integer 157, integer 256, integer 352, integer 0, integer 0)
#3 plugins/BuilderTools/src/czechpmdevs/buildertools/commands/FillCommand(50): czechpmdevs\buildertools\editors\Filler->directFill(object pocketmine\player\Player#26158, object pocketmine\world\Position#96271, object pocketmine\world\Position#121836, string[1] 0, false)
#4 pmsrc/src/command/SimpleCommandMap(225): czechpmdevs\buildertools\commands\FillCommand->execute(object pocketmine\player\Player#26158, string[4] /set, array[1])
#5 pmsrc/src/Server(1291): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#26158, string[6] /set 0)
#6 pmsrc/src/player/Player(1323): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#26158, string[6] /set 0)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(731): pocketmine\player\Player->chat(string[7] //set 0)
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(54): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#122807)
#9 pmsrc/src/network/mcpe/NetworkSession(383): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#93616)
#10 pmsrc/src/network/mcpe/NetworkSession(346): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#122807, string[28] M.//set 0..G.y..............)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(188): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] ..e../N-Q0`.v.X)rv.....o.%......)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[41] .%.X..Z....&....h..d..shQ......i..Y\$.w..)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#24668)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/src/Server(1524): pocketmine\snooze\SleeperHandler->sleepUntil(double 1630529312.5302)
#17 pmsrc/src/Server(1076): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(300): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[13] /root/server/, string[21] /root/server/plugins/)
#19 pmsrc/src/PocketMine(323): pocketmine\server()
#20 pmsrc(11): require(string[57] phar:///root/server/PocketMine-MP.phar/src/PocketMine.php)

PocketMine-MP version: 4.0.0+dev [Protocol 448]
Git commit: be6d9ca3b59d11ac87cb95dfbee5f28490a7ee63
uname -a: Linux 18321 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64
PHP Version: 8.0.8
Zend version: 4.0.8
OS : Linux, linux
```

**Comment by ItsZodiaX** [comment]
Happen to me too.
PocketMine-MP Crash Dump Thu Sep 2 13:53:17 WIB 2021

Error: Invalid subchunk Y coordinate 16
File: pmsrc/src/world/format/Chunk
Line: 357
Type: InvalidArgumentException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: BuilderTools v1.3.0-beta1

Code:
[348] 		$this->dirtyFlags = ~0;
[349] 	}
[350] 
[351] 	public function clearDirtyFlags() : void{
[352] 		$this->dirtyFlags = 0;
[353] 	}
[354] 
[355] 	public function getSubChunk(int $y) : SubChunk{
[356] 		if($y < 0 || $y >= $this->subChunks->getSize()){
[357] 			throw new \InvalidArgumentException("Invalid subchunk Y coordinate $y");
[358] 		}
[359] 		return $this->subChunks[$y];
[360] 	}
[361] 
[362] 	/**
[363] 	 * Sets a subchunk in the chunk index
[364] 	 */
[365] 	public function setSubChunk(int $y, ?SubChunk $subChunk) : void{
[366] 		if($y < 0 or $y >= $this->subChunks->getSize()){
[367] 			throw new \InvalidArgumentException("Invalid subchunk Y coordinate $y");

Backtrace:
#0 plugins/BuilderTools-feature-pm-4.0.0/src/czechpmdevs/buildertools/editors/object/FillSession(216): pocketmine\world\format\Chunk->getSubChunk(integer 16)
#1 plugins/BuilderTools-feature-pm-4.0.0/src/czechpmdevs/buildertools/editors/object/FillSession(108): czechpmdevs\buildertools\editors\object\FillSession->moveTo(integer 156, integer 256, integer 156)
#2 plugins/BuilderTools-feature-pm-4.0.0/src/czechpmdevs/buildertools/editors/Copier(62): czechpmdevs\buildertools\editors\object\FillSession->getBlockAt(integer 156, integer 256, integer 156, integer 0, integer 0)
#3 plugins/BuilderTools-feature-pm-4.0.0/src/czechpmdevs/buildertools/commands/CopyCommand(57): czechpmdevs\buildertools\editors\Copier->copy(object pocketmine\world\Position#454844, object pocketmine\world\Position#444837, object pocketmine\player\Player#29489)
#4 pmsrc/src/command/SimpleCommandMap(247): czechpmdevs\buildertools\commands\CopyCommand->execute(object pocketmine\player\Player#29489, string[5] /copy, array[0])
#5 pmsrc/src/Server(1289): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#29489, string[5] /copy)
#6 pmsrc/src/player/Player(1347): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#29489, string[5] /copy)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(731): pocketmine\player\Player->chat(string[6] //copy)
#8 pmsrc/vendor/idotclub/bedrock-protocol/src/CommandRequestPacket(54): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#353994)
#9 pmsrc/src/network/mcpe/NetworkSession(401): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#451811)
#10 pmsrc/src/network/mcpe/NetworkSession(362): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#353994, integer 448, string[27] M.//copy..M.nJ..?....hV....)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(197): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[31] ..e..O./.dh.]...h...s..e.M.....)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[40] .B.n.....$$yr......y.GVr5..q...2R.GGv!..)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(131): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#23159)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/src/Server(1512): pocketmine\snooze\SleeperHandler->sleepUntil(double 1630565597.6287)
#17 pmsrc/src/Server(1074): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(324): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[32] C:\Users\itszo\Desktop\ZeqaMine\, string[40] C:\Users\itszo\Desktop\ZeqaMine\plugins\)
#19 pmsrc/src/PocketMine(347): pocketmine\server()

PocketMine-MP version: 4.0.0+dev [Protocol 448]
Git commit: 9122316ede873adf266527761118c7ff1a0d09d8-dirty
uname -a: Windows NT ITSZODIAX 10.0 build 19043 (Windows 10) AMD64
PHP Version: 8.0.8
Zend version: 4.0.8
OS : WINNT, win

**Comment by VixikHD** [comment]
Which BuilderTools version do you use?

**Comment by ItsZodiaX** [comment]
I use pm-4.0.0 branch

**Comment by VixikHD** [comment]
I see, but which version?

**Comment by ItsZodiaX** [comment]
I just download the source and run it. No build version

**Comment by VixikHD** [comment]
which commit?

**Comment by ItsZodiaX** [comment]
https://github.com/CzechPMDevs/BuilderTools/commit/9aa3f7efa9172bbf31a70192f2d5e446cffc3db3
