### ISSUE TITLE
Schematics won't paste

### ISSUE THREAD

**Issue by dats07** [CzechPMDevs/BuilderTools#179]
Hello everyone, hopefully someone can help with a problem I am seeing with BuilderTools.  I can load a schematic, and it says it has loaded, but as soon as I try to paste, I get an error saying it isn't loaded.  I am running PocketMine-MP 3.23.1 and BuilderTools 1.2.0.  I have tried multiple schematics.  Are there recommended memory cleanup settings for PocketMine-MP that BuilderTools uses?

Thanks!

**Comment by VixikHD** [comment]
Could you please provide more information such as videos with reproducing the bug?

**Comment by VixikHD** [comment]
I'm closing this due to no response from author.
