### ISSUE TITLE
//paste does not seem to work with //1 and //2

### ISSUE THREAD

**Issue by Paul14912** [CzechPMDevs/BuilderTools#182]
**Describe the bug**
You want to copy a building etc. and paste it into ANOTHER world. So you mark the positions with //1 and //2 and then use //copy. Then you teleport to the other world, use //1 and //2 to mark the positions where it should be pasted (that's what you're meant to do, isn't it?) and then use //paste to paste. 
But it is always pasted in a different place and then too deep. What could be the reason for that? Am I possibly doing something wrong?

**To Reproduce**
1. Copy something with //1, //2 and then //copy
2. Paste it with //1, //2 and then //paste
3. See error

**Expected behavior**
The copied is pasted at the points marked with //1 and //2 and with the correct height.
**Screenshots**

**System information (please complete the following information):**
 - OS: PocketMine 3.25.4
 - php version 8.0
 - BuilderTools Version Release 1.2.0

**Additional context**

**Comment by VixikHD** [comment]
Target position is independent on selected area. Clipboard is being pasted relative to player's position.

![image](https://user-images.githubusercontent.com/40556088/142777495-6a29366f-3aea-4cf1-828f-2e031f4807c4.png)

**Comment by Paul14912** [comment]
So there is no possibility to paste it at a certain position? If not, can you also move it after inserting it with //move(?)
