### ISSUE TITLE
Copy paste bug

### ISSUE THREAD

**Issue by galaxytwenty** [CzechPMDevs/BuilderTools#183]
**Describe the bug**
The Bug Appears When ich paste a copyed ares

**To Reproduce**
1. marked an area with Axe
2. run //copy
3. run //paste

**System information (please complete the following information):**
 - OS: Win10 , IOS, Android
 - php version 8
 - BuilderTools Version 1.2.0 BETA2

**Comment by VixikHD** [comment]
Version 1.2.0-beta2 is outdated, please use [latest version](https://poggit.pmmp.io/p/BuilderTools/1.2.0)

**Comment by galaxytwenty** [comment]
Thanks for Quick answer!.
