### ISSUE TITLE
//fix not working

### ISSUE THREAD

**Issue by PushkarOP** [CzechPMDevs/BuilderTools#190]
**Describe the bug**
//Fix not working

**To Reproduce**
1. Upload a java map in pocketmine 4
2. And do //fix
4. Its says 0 chunks fixed

**Comment by VixikHD** [comment]
Already fixed in https://github.com/CzechPMDevs/BuilderTools/commit/53ed60c01c26fb27131f888ba5ce9fa6318d0611, use [this](https://poggit.pmmp.io/r/151497/BuilderTools_dev-188.phar) dev build untill it got approved on poggit.
