### ISSUE TITLE
Commands to be implemented in 1.4.0

### ISSUE THREAD

**Issue by VixikHD** [CzechPMDevs/BuilderTools#192]
Thanks to a new api, which is going to be added in 1.4.0, there will be open space for new commands. I would personally like to add at least those commands:

| Command | Description |
| --- | --- |
| //sel | https://minecraft-worldedit.fandom.com/wiki///sel |
| //mask | Set mask rule to selected item(s) so it can only affect a particular block type(s) or expression. |
| //replacenear | Replace all block(s) nerby to pattern |
| //hpos1, //hpos2 | Selects position to block which is player looking at |
| //clearclipboard | Clears player clipboard |
| //chunk | Selects the whole chunk as selection |
| //expand | Expand or grow the region selection based on the player's facing or map direction. It can also be expanded to the opposite side with <reverse-amount> at the same time. |
| //line | Creates a line between two positions |
| //drain | Removes liquids from selection |

**Comment by reyyan987** [comment]
Good
