### ISSUE TITLE
//set id dont works

### ISSUE THREAD

**Issue by Pinkglitter2216** [CzechPMDevs/BuilderTools#195]
Unfortunately, the //set id an //fill id command doesn't work. The command only works with //set blockname or //fill blockname. Can you fix it please?

**Comment by Nerahikada** [comment]
Related to #193.
The command is not working in the current release, but it seems to be fixed in the latest development build.

**Comment by Pinkglitter2216** [comment]
Thanks a lot for your really good work!

**Comment by VixikHD** [comment]
This has been already fixed in 1.4
