### ISSUE TITLE
//stacks it does not work

### ISSUE THREAD

**Issue by fernanACM** [CzechPMDevs/BuilderTools#197]
**Describe the bug**
Performing the "pos1, pos2" procedure and executing the //stacks command does nothing.

**System information:**
 - php version [e.g. 7.4.11, 8.0]
 - BuilderTools Version [e.g. dev#142, Release 1.2.0-beta3]

**Comment by VixikHD** [comment]
1.2.0-beta3 is not supported anymore. Please, use newer version which could be found [on poggit](https://poggit.pmmp.io/p/BuilderTools).
