### ISSUE TITLE
Please Urgent

### ISSUE THREAD

**Issue by RodolfoDorfis** [CzechPMDevs/BuilderTools#199]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - php version [e.g. 7.4.11, 8.0]
 - BuilderTools Version [e.g. dev#142, Release 1.2.0-beta3]

**Additional context**
BuilderTools reports all block ids but does not report item ids, eg sword pickaxe etc, this plugin deserves more care for being so good. Thank you

**Comment by VixikHD** [comment]
Please, use the issue template correctly.
