### ISSUE TITLE
add paste

### ISSUE THREAD

**Issue by randoman911** [CzechPMDevs/BuilderTools#2]
not an issue but please add paste using position

**Comment by GamakCZ** [comment]
paste is already added

**Comment by GamakCZ** [comment]
I do not know how you mean "using position"

**Comment by randoman911** [comment]
//1 //2 //paste

**Comment by randoman911** [comment]
please add it

**Comment by GamakCZ** [comment]
there are //paste command with //pos1 //pos2 and //copy it is not enought?

**Comment by randoman911** [comment]
newest build doesnt have //paste and //copy isnt that to copy it so that you can paste

**Comment by GamakCZ** [comment]
do you use 1.1 [DEV] version?

**Comment by randoman911** [comment]
Don't know, can you link me it? I used an updated one on poggit.

**Comment by GamakCZ** [comment]
https://poggit.pmmp.io/ci/CzechPMDevs/BuilderTools/BuilderTools/dev:7
