### ISSUE TITLE
The wand axe does not work whit: Netherite and PMArmorStand plugins

### ISSUE THREAD

**Issue by MrBlasyMSK** [CzechPMDevs/BuilderTools#205]
**Describe the bug**
Apparently it was not corrected, I closed my issue #201 but the problem remains, the good thing is that I have found the plugins that interfere with BuilderTools and make the axe not work.

If you install 1 of those 2 plugins with BuilderTools when you use the //wand command it will give you a non-enchanted axe and without the properties to mark positions.

(All other commands like //1 //replace etc. work)
I have been 2 hours restarting and removing plugins to verify which ones gave the error, I will also open issues in the respective plugins to investigate the error, but just in case check that everything is correct in the //wand command.

**To Reproduce**
1. Install Netherite + PMArmorStand + BuilderTools
2. Restart the server and enter
3. Use the command //wand
4. Look at how the enchanted axe does not appear and does not let you mark the positions either.

**Expected behavior**
That the axe will work regardless of which plugin you add as long as it does not affect the code directly.

**Screenshots**
**Here's what happens if you use BuilderTools with +70 different plugins (works fine)**
![Captura de pantalla (497)](https://user-images.githubusercontent.com/85447029/159792528-2e9a8d66-777f-412b-801f-9d1cd2d85337.png)
**This is what happens if you install any of the 2 plugins mentioned above (does not work)**
![Captura de pantalla (498)](https://user-images.githubusercontent.com/85447029/159792696-687b5e58-51e4-4e98-8c0a-b39c67f47032.png)

**System information (please complete the following information):**
 - OS: linux
 - php version 8.0.16
 - BuilderTools Version: dev218

**Additional context**
X

**Comment by xXRyzen** [comment]
I have neither of those mentioned plugins, but I am getting the same issue. Wand appears and labeled as a wand but nothing happens when using it, just breaks the block without setting position.

**Comment by VixikHD** [comment]
Seems like it is already fixed in latest 1.4.0 commit
