### ISSUE TITLE
//fill Command Not Working

### ISSUE THREAD

**Issue by DaDevGuy** [CzechPMDevs/BuilderTools#207]
**Describe the bug**
//fill command is not working.

**To Reproduce**
1. Go to 'Server'
2. Use command '//fill'
3. See error

**Expected behavior**
Should Replace Blocks with provided id.

**Screenshots**
No Screenshot because i am not in server right now.

**System information (please complete the following information):**
 - OS: [Ubuntu]
 - PHP Version: [8.0]
 - BuilderTools Version: [1.3.1]

**Additional context**
None.

**Comment by TukangM** [comment]
maybe not work on map leveldb format?

**Comment by DaDevGuy** [comment]
no bro 
i just created new world from BuilderTools this shouldwork

**Comment by DaDevGuy** [comment]
um please fix this bug cuz this is a major plugin

**Comment by TukangM** [comment]
> um please fix this bug cuz this is a major plugin

i am not dev php

**Comment by PocketMiner92** [comment]
@DaDevGuy xd you are a "Dev" fix this self

**Comment by PocketMiner92** [comment]
Or use another Software
PHP for Softwares are really funny.

**Comment by TukangM** [comment]
> no bro i just created new world from BuilderTools this shouldwork

//fill cmd work if name block is non id's. //fill grass . not //fill 2

**Comment by DaDevGuy** [comment]
ok
