### ISSUE TITLE
erorr on map leveldb format //fill

### ISSUE THREAD

**Issue by TukangM** [CzechPMDevs/BuilderTools#208]
**Describe the bug**

**To Reproduce**

**Expected behavior**
[BuilderTools] Error While processing the command: No blocks specified in string 0
world type leveldb
Pocketmine.yml : 
level-settings:
  #The default format that worlds will use when created
  default-format: leveldb

**Screenshots**
![image](https://user-images.githubusercontent.com/91467886/162650239-04a36ebc-f777-4e5b-aff1-aed8acfc25ed.png)

**System information (please complete the following information):**
 - OS: [linux] (host pterodactyl)
 - PHP Version: [8.0.17]
 - BuilderTools Version: [e.g. dev#219, [BuilderTools_dev-219.phar](https://poggit.pmmp.io/r/169562/BuilderTools_dev-219.phar)]

**Additional context**
translate: Add any other context about the problem here.
when I'm using builder tools and I've chosen where to //fill it using //wand . and an error appears
[BuilderTools] Error While processing the command: No blocks specified in string 0

**Comment by VixikHD** [comment]
Use "air" instead of "0"

**Comment by Agus39** [comment]
All item ID cannot be used when //fill

**Comment by Agus39** [comment]
> Use "air" instead of "0"

All item ID cannot be used when //fill

**Comment by ReyyanGamer** [comment]
> > Use "air" instead of "0"
> 
> All block ID cannot be used when //fill. If you use the block name for //fill and the block name has spaces for example* "yellow terracotta" it will get an error like this [Builder Tools] Error While processing the command: No blocks specified in string yellow terracotta

Then do Yellow_Terracotta

**Comment by VixikHD** [comment]
This issue should be fixed in 1.4.0
