### ISSUE TITLE
incomplete schematics when pasted

### ISSUE THREAD

**Issue by Bencraft0** [CzechPMDevs/BuilderTools#219]
when you paste very large schematics, they do not paste completely, but a fraction of them

**Comment by VixikHD** [comment]
Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.

Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

Also, it would help to upload schematic, you attemted to load.
