### ISSUE TITLE
API5 Error issue

### ISSUE THREAD

**Issue by cherrychip8293** [CzechPMDevs/BuilderTools#223]
This error occurs when attempting to copy the specified area using the //copy command.
Below is the error log caused by the attempt to do so.

 [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\world\format\SubChunk::getFullBlock()" (EXCEPTION) in "plugins/BuilderTools_v2.0.0-dev.phar/src/czechpmdevs/buildertools/editors/object/FillSession" at line 100
--- Stack trace ---
  #0 plugins/BuilderTools_v2.0.0-dev.phar/src/czechpmdevs/buildertools/shape/Cuboid(147): czechpmdevs\buildertools\editors\object\FillSession->getBlockAt(int 9, int 10, int -229, null)
  #1 plugins/BuilderTools_v2.0.0-dev.phar/src/czechpmdevs/buildertools/session/selection/CuboidSelection(189): czechpmdevs\buildertools\shape\Cuboid->read(object czechpmdevs\buildertools\blockstorage\BlockArray#314241)
  #2 plugins/BuilderTools_v2.0.0-dev.phar/src/czechpmdevs/buildertools/commands/clipboard/CopyCommand(44): czechpmdevs\buildertools\session\selection\CuboidSelection->saveToClipboard(object pocketmine\math\Vector3#314172)
  #3 pmsrc/src/command/SimpleCommandMap(208): czechpmdevs\buildertools\commands\clipboard\CopyCommand->execute(object pocketmine\player\Player#159788, string[5] /copy, array[0])
  #4 pmsrc/src/Server(1433): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#159788, string[5] /copy)
  #5 pmsrc/src/player/Player(1446): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#159788, string[5] /copy)
  #6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(735): pocketmine\player\Player->chat(string[6] //copy)
  #7 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#345583)
  #8 pmsrc/src/network/mcpe/NetworkSession(453): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#401889)
  #9 pmsrc/src/network/mcpe/NetworkSession(409): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#345583, string[28] M.//copy..C}.........*Rs...4)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(190): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] ..e..O./.d..\..w......n..*...`..)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[41] ... .v_........D..6....v.Wx.....~C.......)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(117): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#55820)
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(126): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #16 pmsrc/src/Server(1692): pocketmine\snooze\SleeperHandler->sleepUntil(float 1676369772.4158)
  #17 pmsrc/src/Server(1049): pocketmine\Server->tickProcessor()
  #18 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[9] /root/pm/, string[17] /root/pm/plugins/)
  #19 pmsrc/src/PocketMine(362): pocketmine\server()
  #20 pmsrc(11): require(string[53] phar

**Comment by dadodasyra** [comment]
Same with schematics create

**Comment by VixikHD** [comment]
This should not occur anymore
