### ISSUE TITLE
I cant get the pos1 and the pos2 via code 

### ISSUE THREAD

**Issue by galaxytwenty** [CzechPMDevs/BuilderTools#224]
**Is your feature request related to a problem? Please describe.**
i cant get the pos1 and the pos2 via code 

**Describe the solution you'd like**

    public function getSecondPosition()
    {
        return $this->secondPosition;
    }

    public function getFirstPosition()
    {
        return $this->firstPosition;
    }

**Describe alternatives you've considered**
No alternatives ?

**Additional context**
so it would good when i can get the pos1 and pos2 via code

**Comment by VixikHD** [comment]
In 1.3 it is possible throughout [Selectors class](https://github.com/CzechPMDevs/BuilderTools/blob/legacy/1.3/src/czechpmdevs/buildertools/Selectors.php#L104), In 1.4 it sounds as [XY problem](https://xyproblem.info/). However, in 1.4 those positions became dependent on current selection type, meaning each selection type might have different position count selected. If you'd like to, you can add your own selection type (for example, by extending CuboidSelection) so you can add your own methods, even getters for those points.
