### ISSUE TITLE
No //fix command visible

### ISSUE THREAD

**Issue by MBG1337** [CzechPMDevs/BuilderTools#229]
**Describe the bug**
When i type //fix in the chat no command suggestion pops up nor does it work if i type //fix

**To Reproduce**
1. Open chat
2. click on the chat box
3. type //fix and press enter.

**Expected behavior**
Seeing the //fix command suggestion and response when i type //fix

**Screenshots**
![image](https://github.com/CzechPMDevs/BuilderTools/assets/108623200/28034480-5bd0-4538-95de-c2c4ea5dcd40)
![image](https://github.com/CzechPMDevs/BuilderTools/assets/108623200/7d60a27b-2358-46ce-9339-09c80f397593)
![image](https://github.com/CzechPMDevs/BuilderTools/assets/108623200/b9c15b85-9ed4-4d2f-9faa-b6c18e2c48fa)

**System information (please complete the following information):**
 - OS: Windows 11 Pro
 - php version 8.1.0
 - BuilderTools Version 2.0.0-beta1

**Additional context**
N/A

**Comment by Nyrok** [comment]
Hello, referring to https://github.com/CzechPMDevs/BuilderTools/commit/92a3848987833d392571906a798ccd9295c07e89, the fix command has been removed with the java-bedrock world convert system.
