### ISSUE TITLE
Errors on commands

### ISSUE THREAD

**Issue by kevinishawesome** [CzechPMDevs/BuilderTools#23]
Errors with **undo** command
Errors with **flip** command 

The commands just show error while being used

**Comment by iShabzz102** [comment]
I don't see no errors. Close this.

**Comment by lcyLand** [comment]
Anything command you run //set, //replace and a few others, it will say there is nothing to undo. You can't undo what you just used //set for?

**Comment by GamakCZ** [comment]
Fixed in last commit
