### ISSUE TITLE
Missing Selectors

### ISSUE THREAD

**Issue by tgwaste** [CzechPMDevs/BuilderTools#231]
Hi,
  What happened to:
use czechpmdevs\buildertools\Selectors;
(new Selectors)->addSelector();

Can you tell me what the equivalent is for 2.0.0?

**Comment by VixikHD** [comment]
https://github.com/CzechPMDevs/BuilderTools/issues/224

**Comment by tgwaste** [comment]
I dont want to GET the positions.  I want to SET the positions so that when I do /fill for example your app knows the two positions.

**Comment by tgwaste** [comment]
This seems to work:
```
$selector = SessionManager::getInstance()->getSession($player)->getSelectionHolder();
$selector->handleWandAxeBlockClick($position1);
$selector->handleWandAxeBlockBreak($position2);
```
