### ISSUE TITLE
Rotate feature

### ISSUE THREAD

**Issue by GamakCZ** [CzechPMDevs/BuilderTools#45]
I left a review on the pmmp page aswell, but i'd like to suggest it here aswell. 

Would it be possible to change //wand to 1 specific item as a wooden axe as it would be time saving and much more efficient.

Very good job so far though, keep it up!

_Originally posted by @Landy005 in https://github.com/CzechPMDevs/BuilderTools/issues/44#issuecomment-466390598_

**Comment by GamakCZ** [comment]
As for rotation i think i'd be better and more efficient aswell if it were like this:

//rotate 90 0 0 to rotate it 90 degrees on Y around the //copy spot
//rotate 0 90 0 to rotate it 90 degrees on x around the //copy spot
//rotate 0 0 90 to rotate it 90 degrees on z around the //copy spot

and for flip i'd suggest it gets mirrored the way you look at. For instance you copy your build than look up it and it will flip upside down. If you'd look right and //flip it would mirror to the right side (including mirroring your current //copy position.

These are recommendations by the build community of McBe as this is what we're used to in java edition.

Originally posted by @Landy005 in [#44 (comment)](https://github.com/CzechPMDevs/BuilderTools/issues/44#issuecomment-466390598)

**Comment by GamakCZ** [comment]
1.3.0 TODO

**Comment by Wertzui123** [comment]
Yay //rotate would be cool

**Comment by Landy005** [comment]
any update on this?

**Comment by Landy005** [comment]
perhaps give //block id also a tool like a wooden sword just like //wand a wooden axe, saves time to not constantly switch modes but switch slots instead ;)

**Comment by GamakCZ** [comment]
Done 🎉
