### ISSUE TITLE
Suggestion or Bug

### ISSUE THREAD

**Issue by SuperAdam47** [CzechPMDevs/BuilderTools#46]
![image](https://user-images.githubusercontent.com/16169771/53298173-09ca7580-383b-11e9-9097-2d38c4fa6d80.png)

- Don't fixing this blocks

**Comment by GamakCZ** [comment]
id?

**Comment by GamakCZ** [comment]
it seems like piston, thats pmmp error

**Comment by SuperAdam47** [comment]
I dont known id

**Comment by tootsqueak** [comment]
doing //set and //replace and //fill keeps crashing it comes up with internal server error

**Comment by GamakCZ** [comment]
use newest dev version, 1.12 new

**Comment by tootsqueak** [comment]
all the plugins are updated and even the phar

**Comment by tootsqueak** [comment]
when i look in the water everything is black you can only see the player nothing this is this plugin when ever i added it this happend

**Comment by provsnoobgaming** [comment]
thats client side or might be chunk errors

**Comment by GamakCZ** [comment]
It seems like piston, for that you have to implement some redstone plugin. Also author of this issue seems to be inactive. So I can't fix it for now.
