### ISSUE TITLE
dark areas

### ISSUE THREAD

**Issue by ghost** [CzechPMDevs/BuilderTools#52]
after filling, it leaves some dark areas where the blocks are black...
![Minecraft Screenshot 2019 03 25 - 21 35 49 16](https://user-images.githubusercontent.com/32599317/54970007-2515c700-4f46-11e9-9986-ed29f45fdf65.png)

**Comment by GamakCZ** [comment]
I can't reproduce it.

**Comment by VixikHD** [comment]
I don't recognise this in last commits, if you reproduce the bug with latest dev version, create a new issue for that.
