### ISSUE TITLE
Stuck at loading builder tools when there's a schematic file in schematics folder

### ISSUE THREAD

**Issue by ghost** [CzechPMDevs/BuilderTools#53]
so im trying to load a schematic file using builder tools but when i put my schematic file in schematics folder, builder tools stops at 'enabling'

**Comment by GamakCZ** [comment]
there are two ways to fix:
1) Wait few secs when the schematic is loaded
2) Change [config line 13](https://github.com/CzechPMDevs/BuilderTools/blob/master/BuilderTools/resources/config.yml#L13) to oncommand

**Comment by GamakCZ** [comment]
Maybe fix it through custom thread

**Comment by GamakCZ** [comment]
Schematics are now loaded using async tasks
