### ISSUE TITLE
//fix command crash!!

### ISSUE THREAD

**Issue by derrenrafa** [CzechPMDevs/BuilderTools#58]
I try to fix skywars from Java edition of i say //Wand the PocketMine was crash plss help

**Comment by GamakCZ** [comment]
can you provide more information? like a crashdump file...

**Comment by Alemiz112** [comment]
I can. Its due to:
![image](https://user-images.githubusercontent.com/45739737/66698319-589b2180-ecdd-11e9-8068-17655bfaa92b.png)

**Comment by Alemiz112** [comment]
Fixed in [Pre-Release](https://github.com/CzechPMDevs/BuilderTools/tree/pre-release) branch.
