### ISSUE TITLE
Naturalizer Dump Error

### ISSUE THREAD

**Issue by dearminder** [CzechPMDevs/BuilderTools#59]
/naturalize gives
[Server thread/CRITICAL]: Error: "Call to undefined method czechpmdevs\buildertools\editors\object\BlockList::saveBlockMap()" (EXCEPTION) in "plugins/BuilderTools-master/src/czechpmdevs/buildertools/editors/Naturalizer" at line 56

**Comment by GamakCZ** [comment]
thx for report

**Comment by GamakCZ** [comment]
Fixed in latest dev version

**Comment by sc00scoc** [comment]
saveBlockMap
"Call to undefined method czechpmdevs\buildertools\editors\object\BlockList::saveBlockMap()"
