### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mikeygio10** [CzechPMDevs/BuilderTools#61]
13.07 15:28:56 [Server] Server thread/CRITICAL Error: "Class 'pocketmine\network\mcpe\protocol\FullChunkDataPacket' not found" (EXCEPTION) in "plugins/BuilderTools.phar/src/czechpmdevs/buildertools/editors/Filler" at line 133
13.07 15:28:56 [Server] Server thread/DEBUG #0 plugins/BuilderTools.phar/src/czechpmdevs/buildertools/editors/Filler(163): czechpmdevs\buildertools\editors\Filler->czechpmdevs\buildertools\editors\{closure}(object pocketmine\level\Level, integer 166, integer 169, integer 267, integer 261)
13.07 15:28:56 [Server] Server thread/DEBUG #1 plugins/BuilderTools.phar/src/czechpmdevs/buildertools/commands/FillCommand(84): czechpmdevs\buildertools\editors\Filler->fill(object JackMD\NameSpaceRemover\CustomPlayer, object czechpmdevs\buildertools\editors\object\BlockList)
13.07 15:28:56 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(270): czechpmdevs\buildertools\commands\FillCommand->execute(object JackMD\NameSpaceRemover\CustomPlayer, string[4] /set, array[1])
13.07 15:28:56 [Server] Server thread/DEBUG #3 src/pocketmine/Server(2029): pocketmine\command\SimpleCommandMap->dispatch(object JackMD\NameSpaceRemover\CustomPlayer, string[6] /set 0)
13.07 15:28:56 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2231): pocketmine\Server->dispatchCommand(object JackMD\NameSpaceRemover\CustomPlayer, string[6] /set 0)
13.07 15:28:56 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(240): pocketmine\Player->chat(string[7] //set 0)
13.07 15:28:56 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
13.07 15:28:56 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
13.07 15:28:56 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
13.07 15:28:56 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
13.07 15:28:56 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3124): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
13.07 15:28:56 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
13.07 15:28:56 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 70.105.172.190 57040, object raklib\protocol\EncapsulatedPacket, integer 0)
13.07 15:28:56 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
13.07 15:28:56 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
13.07 15:28:56 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
13.07 15:28:56 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
13.07 15:28:56 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2348): pocketmine\snooze\SleeperHandler->sleepUntil(double 1563031735.8281)
13.07 15:28:56 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
13.07 15:28:56 [Server] Server thread/DEBUG #19 src/pocketmine/Server(1784): pocketmine\Server->start()
13.07 15:28:56 [Server] Server thread/DEBUG #20 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
13.07 15:28:56 [Server] Server thread/DEBUG #21 (1): require(string[114] phar:///PMMP-1.12.0-Latest-Stable.)

**Comment by GamakCZ** [comment]
#60
