### ISSUE TITLE
[Sugestion] //help?

### ISSUE THREAD

**Issue by dearminder** [CzechPMDevs/BuilderTools#63]
Is it possible to move all commands from /help and move it to //help ?
It may be kinda stupid but whenever i want to use help it dumps all BuilderTools commands at first and its a bit annoying. If all commands starts as // then maby you could add //help for only BuilderTools ?

**Comment by GamakCZ** [comment]
Commands //help and //? are client side, so I can't set them. However you can use //commands to display all BT commands.
