### ISSUE TITLE
1.1 phar link is dead?

### ISSUE THREAD

**Issue by karikera** [CzechPMDevs/BuilderTools#65]
https://github.com/CzechPMDevs/BuilderTools/releases/download/1.1.0/BuilderTools_v1.1.0.phar

i cannot download it :(

**Comment by provsnoobgaming** [comment]
https://poggit.pmmp.io/r/62327/BuilderTools_dev-66.phar
idiot

**Comment by karikera** [comment]
@provsnoobgaming also I found that but README link is still broken.

**Comment by provsnoobgaming** [comment]
@karikera we don't need that it was last updated 7 months ago which means that they are not going to care about you can also just download zip and extract and run plugin from folder with dev tools

**Comment by karikera** [comment]
@provsnoobgaming I just want to keep open this issue
Do you want close it?
or just you want say idiot?
whatever..  I don't care you anymore

**Comment by GamakCZ** [comment]
Poggit sometimes doesn't work, tell PMMP team to fix that.
