### ISSUE TITLE
Move and naturalizer not work at all

### ISSUE THREAD

**Issue by dapwestwood** [CzechPMDevs/BuilderTools#66]
When i set pos1 n 2 i run //naturalize it doesnt work, n there is no logs or error just no work, it same for //move it just delete block on it, i run //move x y z. That i fill with my coordinate. Thank you,, hope u help me

**Comment by GamakCZ** [comment]
What version are you using?

**Comment by ZZWILLIAMXXTrue** [comment]
Same is happing to me, using 1.2.0-beta2

**Comment by GamakCZ** [comment]
Probably it's already fixed
