### ISSUE TITLE
//naturalize is broken

### ISSUE THREAD

**Issue by AL3XPI** [CzechPMDevs/BuilderTools#67]
//naturalize kicks me out of my server with the error "internal server error" 
console log (i hid sensitive info):
![image](https://user-images.githubusercontent.com/35903333/62211287-11eb8b80-b36c-11e9-92b3-938574f65c05.png)

**Comment by AL3XPI** [comment]
@GamakCZ

**Comment by GamakCZ** [comment]
Fixed in latest dev build. https://poggit.pmmp.io/r/62327/BuilderTools_dev-66.phar
