### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by diamondkorben** [CzechPMDevs/BuilderTools#68]
It shows enabled then it kills the server (only plugin on the server)

**Comment by GamakCZ** [comment]
Are you loading some schematics?

**Comment by diamondkorben** [comment]
No i am not

**Comment by diamondkorben** [comment]
It worked without the schematics but whennibdid it kills the server

**Comment by GamakCZ** [comment]
pmmp is too slow to load schematic fast. So if you want to remove the lag when server starts, gi to config.yml and change schematic loading to 'oncommand'
