### ISSUE TITLE
can you add //hsphere and //hcube 

### ISSUE THREAD

**Issue by brexmania123** [CzechPMDevs/BuilderTools#7]
hello i was was wondering if you can add //hsphere and //hcube please. These are the hollow version of the original command but not erasing anything from the inside of the hollow version. It will make it easier to add like domes and hollow cubes. Thank you for listening, and i hope you add these soon

**Comment by thelucyclub** [comment]
any update?

**Comment by GamakCZ** [comment]
Moved to #32
