### ISSUE TITLE
Sponge schematics aren't supported

### ISSUE THREAD

**Issue by Kingofchaos0214-MC** [CzechPMDevs/BuilderTools#72]
Everytime i try to paste a schematic from any website, I get this error... [buildertools] Invalid schematic format (Sponge) Isn't Supported can u help me? I dont use this much so if you CAN, can u contact me on discord? my tag is Kingofchaos0214#0001. Here works too for responding though!

**Comment by GamakCZ** [comment]
Official worldedit for java versions supports both formats (sponge, mcedit). So if you want load mcedit format, you must recompile schematic using worldedit on mc java.

**Comment by Kingofchaos0214-MC** [comment]
Hello! I’m using it on a BEDROCK edition server... how would that work
then?

**Comment by GamakCZ** [comment]
I know. I will try implement it.

**Comment by Kingofchaos0214-MC** [comment]
Ah! So it’s not implemented yet. Got it. Do you mind emailing me when you
do add it please?

**Comment by Kingofchaos0214-MC** [comment]
This email is fine.

**Comment by GamakCZ** [comment]
It isn't simple as you think 😄... It have been implemented, if so.

**Comment by Kingofchaos0214-MC** [comment]
Okay. Do you think if you do get it implemented, you could email me and let
me know though?

**Comment by DemonicNephalem** [comment]
@GamakCZ  since this was 7-9 months ago is there any updates about implementing sponge schematics?

**Comment by VixikHD** [comment]
I cannot find any sponge schematics nowadays. Without it I am not able to implement them. If someone send me some, I would implement them.
