### ISSUE TITLE
Can you add this

### ISSUE THREAD

**Issue by jennocool** [CzechPMDevs/BuilderTools#75]
Is there an way that you can add an feature that you can sort of copy all blocks from one world to another world not duplicating the world
If this is not possible do you know an way how?

(Or just simply copy and paste way over 1000 blocks)
I know pocketmine can't handel this but maybe there is an way to slowly copy and paste chunck by chunck

**Comment by GamakCZ** [comment]
//copy //paste //replace ... or duplicate the world...
I'm really don't thinking about chunk copy-paste commands.

**Comment by jennocool** [comment]
My world is bugged so I need to copy the blocks

**Comment by GamakCZ** [comment]
you can try do it through nbt editor on win
