### ISSUE TITLE
Internal server error while //set dirt

### ISSUE THREAD

**Issue by Invy55** [CzechPMDevs/BuilderTools#76]
Hello, when I select a zone and then do anything on it, server kicks me, the area get edited but it throw an error. I'm using latest version of PocketMine (that one exited yestersay), but i don't know which version of this plugin.-.

**[18:08:49] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\LevelChunkPacket::$chunkX" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 160**

> [18:08:49] [Server thread/DEBUG]: #0 plugins/ItemCase.phar/src/aliuly/itemcasepe/Main(281): pocketmine\network\mcpe\protocol\DataPacket->__get(string[6] chunkX)
> [18:08:49] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): aliuly\itemcasepe\Main->onSendPacket(object pocketmine\event\server\DataPacketSendEvent)
> [18:08:49] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object aliuly\itemcasepe\Main, object pocketmine\event\server\DataPacketSendEvent)
> [18:08:49] [Server thread/DEBUG]: #3 src/pocketmine/event/Event(95): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent)
> [18:08:49] [Server thread/DEBUG]: #4 src/pocketmine/Player(3209): pocketmine\event\Event->call()
> [18:08:49] [Server thread/DEBUG]: #5 src/pocketmine/Player(3234): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\LevelChunkPacket, boolean , boolean )
> [18:08:49] [Server thread/DEBUG]: #6 plugins/BuilderTools.phar/src/czechpmdevs/buildertools/editors/Filler(143): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\LevelChunkPacket)
> [18:08:49] [Server thread/DEBUG]: #7 plugins/BuilderTools.phar/src/czechpmdevs/buildertools/editors/Filler(169): czechpmdevs\buildertools\editors\Filler->czechpmdevs\buildertools\editors\{closure}(object pocketmine\level\Level, integer 322, integer 238, integer 324, integer 239)
> [18:08:49] [Server thread/DEBUG]: #8 plugins/BuilderTools.phar/src/czechpmdevs/buildertools/commands/FillCommand(84): czechpmdevs\buildertools\editors\Filler->fill(object pocketmine\Player, object czechpmdevs\buildertools\editors\object\BlockList)
> [18:08:49] [Server thread/DEBUG]: #9 src/pocketmine/command/SimpleCommandMap(270): czechpmdevs\buildertools\commands\FillCommand->execute(object pocketmine\Player, string[4] /set, array[1])
> [18:08:49] [Server thread/DEBUG]: #10 src/pocketmine/Server(2026): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[9] /set dirt)
> [18:08:49] [Server thread/DEBUG]: #11 src/pocketmine/Player(2257): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[9] /set dirt)
> [18:08:49] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(245): pocketmine\Player->chat(string[10] //set dirt)
> [18:08:49] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
> [18:08:49] [Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(111): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
> [18:08:49] [Server thread/DEBUG]: #15 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
> [18:08:49] [Server thread/DEBUG]: #16 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(111): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
> [18:08:49] [Server thread/DEBUG]: #17 src/pocketmine/Player(3158): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
> [18:08:49] [Server thread/DEBUG]: #18 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
> [18:08:49] [Server thread/DEBUG]: #19 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 192.168.0.20 51115, object raklib\protocol\EncapsulatedPacket, integer 0)
> [18:08:49] [Server thread/DEBUG]: #20 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
> [18:08:49] [Server thread/DEBUG]: #21 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
> [18:08:49] [Server thread/DEBUG]: #22 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
> [18:08:49] [Server thread/DEBUG]: #23 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
> [18:08:49] [Server thread/DEBUG]: #24 src/pocketmine/Server(2349): pocketmine\snooze\SleeperHandler->sleepUntil(double 1577729329.051)
> [18:08:49] [Server thread/DEBUG]: #25 src/pocketmine/Server(2203): pocketmine\Server->tickProcessor()
> [18:08:49] [Server thread/DEBUG]: #26 src/pocketmine/Server(1785): pocketmine\Server->start()
> [18:08:49] [Server thread/DEBUG]: #27 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[37] C:\Users\mrcso\Desktop\PocketMine-MP\, string[45] C:\Users\mrcso\Desktop\PocketMine-MP\plugins\)
> [18:08:49] [Server thread/DEBUG]: #28 src/pocketmine/PocketMine(295): pocketmine\server()
> [18:08:49] [Server thread/DEBUG]: #29 (1): require(string[92] phar://C:/Users/mrcso/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Po)
> [18:08:49] [Server thread/DEBUG]: [PurePerms] Unregistering player Invy55...
> [18:08:49] [Server thread/INFO]: Invy55 left the game

**Comment by GamakCZ** [comment]
That's caused by ItemCase plugin

**Comment by Invy55** [comment]
Is there any way to keep both the plugins?

**Comment by GamakCZ** [comment]
I can try debug it, however the best way is to submit this issue to the ItemCase plugin

**Comment by Invy55** [comment]
> I can try debug it, however the best way is to submit this issue to the ItemCase plugin

Yeah, but I removed itemCase and the chunks still doesn't render and stop doesn't stop

**Comment by Invy55** [comment]
SOLVED: all the problem were created from a uge schematic in the schematic folder
