### ISSUE TITLE
//set

### ISSUE THREAD

**Issue by MonoAdrian23** [CzechPMDevs/BuilderTools#77]
Latest Builder Tools Version!
//set = Internal Server Error
Pocketmine 3.11.2

**Comment by Elementmax757** [comment]
Can you guys make it so that //flip doesn’t flip your build upside down, and instead you can flip it like //flip east //flip north //flip south and //flip west like other world edit things do? if so that would be a lot easier and doing /rotate, I would like to do /rotate 70 //rotate 90 and things.

**Comment by GamakCZ** [comment]
I need the dump which is debugged while error. However for me it normally works.
