### ISSUE TITLE
//flip and rotata

### ISSUE THREAD

**Issue by Elementmax757** [CzechPMDevs/BuilderTools#78]
Can you guys make it so that //flip doesn’t flip your build upside down, and instead you can flip it like //flip east //flip north //flip south and //flip west like other world edit things do? if so that would be a lot easier and doing /rotate, I would like to do /rotate 70 //rotate 90 and things.

**Comment by GamakCZ** [comment]
I don't think it's possible to rotate objects about 70 degress xdd. But I'm trying to implement it!

**Comment by GamakCZ** [comment]
rotate fixed in last commit
