### ISSUE TITLE
Naturalize Bug

### ISSUE THREAD

**Issue by Nerahikada** [CzechPMDevs/BuilderTools#83]
## Description:
When I run a command on a 5x5x5 cube, it looks like this.

![Minecraft 2020_03_27 9_16_23](https://user-images.githubusercontent.com/15967582/77708588-cfb63f00-700b-11ea-8228-657d712a1dd1.png)
![Minecraft 2020_03_27 9_16_33](https://user-images.githubusercontent.com/15967582/77708592-d2b12f80-700b-11ea-8ba0-fa80b8de5873.png)

## Environments:
PocketMine-MP: 3.11.6
BuilderTools commit: a307253800c0ee25c24e047d278dd5e9ef814276

**Comment by GamakCZ** [comment]
Finally some good description of the bug
