### ISSUE TITLE
It takes me off the server

### ISSUE THREAD

**Issue by 1AssassinGhost1** [CzechPMDevs/BuilderTools#89]
Hello and above all it will not be English and I will try to put it in English. A few days ago I used its buildertools but I do not suddenly miss me every time I do a thing with its plugins takes me out of the server or I do not close the server I do not know what is or something I do not know that it fails uninstall it several times and nothing deletes the data and the phar and nothing helps me please I can not do anything or build hope your message as soon as possible. And if you want to try go into my server 1.14.60 only IP Hello and above all it will not be English and I will try to put it in English. A few days ago I used its buildertools but I do not suddenly miss me every time I do a thing with its plugins takes me out of the server or I do not close the server I do not know what is or something I do not know that it fails uninstall it several times and nothing deletes the data and the phar and nothing helps me please I can not do anything or build hope your message as soon as possible. And if you want to try, go to my server 1.14.60 only IP SpartaCraft.play-mc.net Hello and above all it will not be English and I will try to put it in English. A few days ago I used its buildertools but I do not suddenly miss me every time I do a thing with its plugins takes me out of the server or I do not close the server I do not know what is or something I do not know that it fails uninstall it several times and nothing deletes the data and the phar and nothing helps me please I can not do anything or build hope your message as soon as possible. And if you want to try, go to my server 1.14.60 only IP SpartaCraft.play-mc.net

**Comment by GamakCZ** [comment]
Use released version
