### ISSUE TITLE
Request : Optional Coords for pos

### ISSUE THREAD

**Issue by cyphr3x** [CzechPMDevs/BuilderTools#91]
It would be cool if you could optionally add X/Y/Z coords to //pos for precision.

**Comment by Endermanbugzjfc** [comment]
> It would be cool if you could optionally add X/Y/Z coords to //pos for precision.

**Here you go: https://github.com/Endermanbugzjfc/BuilderTools**

**Comment by cyphr3x** [comment]
thank you!
